# docker stack deploy -c stack.yml dns3l
# or: docker-compose -f stack.yml up [--build]
# visit: http[s]://swarm-ip, http[s]://localhost, or http[s]://host-ip

version: '3.1'

services:
  db:
    image: mariadb
    container_name: dns3l-mariadb
    restart: unless-stopped
    # environment:
    #   MARIADB_ROOT_PASSWORD: secret
    env_file:
      .env/db
    volumes:
      - dns3l-db:/var/lib/mysql
    networks:
      - dns3l
    dns_search: .

  ingress:
    image: ghcr.io/dns3l/ingress
    container_name: dns3l-ingress
    restart: unless-stopped
    # volumes:
    #   - .env/nginx.conf:/etc/nginx.conf:ro
    env_file:
      .env/ingress
    networks:
      - dns3l
    dns_search: .
    ports:
      - 443:443
    depends_on:
      web:
        condition: service_started
      dns3ld:
        condition: service_started

  web:
    image: ghcr.io/dns3l/web
    container_name: dns3l-web
    restart: unless-stopped
    # volumes:
    #   - .env/nuxt.config.js:/etc/nuxt.config.js:ro
    env_file:
      .env/web
    networks:
      - dns3l
    dns_search: .
    healthcheck:
      disable: false
      test: "curl -fsk -o /dev/null http://localhost:3000"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  sra:
    image: ghcr.io/dns3l/sra
    container_name: dns3l-sra
    restart: unless-stopped
    # volumes:
    #   - .env/stepca.conf:/etc/stepca.conf.json:ro
    # environment:
    #   HTTP_PROXY:
    #   HTTPS_PROXY:
    #   NO_PROXY:
    env_file:
      .env/sra
    networks:
      - dns3l
    dns_search: .
    depends_on:
      - db

  # stack external auth1..n
  auth1:
    image: ghcr.io/dns3l/auth
    container_name: dns3l-auth1
    restart: unless-stopped
    # volumes:
    #   - .env/dex1.conf:/etc/dex.conf.yml:ro
    env_file:
      .env/auth1
    networks:
      - dns3l
    dns_search: .
    healthcheck:
      disable: false
      test: "curl -fsk -o /dev/null https://localhost:5554/auth/.well-known/openid-configuration"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 15s

  dns3ld:
    image: ghcr.io/dns3l/dns3ld
    container_name: dns3l-dns3ld
    restart: unless-stopped
    volumes:
      - .env/dns3ld.conf:/etc/dns3ld.conf.yml:ro
    # environment:
    #   HTTP_PROXY:
    #   HTTPS_PROXY:
    #   NO_PROXY:
    env_file:
      .env/dns3ld
    networks:
      - dns3l
    dns_search: .
    depends_on:
      db:
        condition: service_started
    healthcheck:
      disable: false
      test: "curl -fs -o /dev/null http://localhost:8880/api/info"
      interval: 15s
      timeout: 5s
      retries: 3
      start_period: 10s

volumes:
  dns3l-db:

networks:
  dns3l:
    external: false
