name: Build, release and publish
on:
  push:
    branches:
      - master
      - next
      - beta
      - alpha
      - '*.x'
    paths-ignore:
      - '**.md'
  pull_request:
    types:
      - closed
    paths-ignore:
      - '**.md'

jobs:
  release:
    name: Build, release and publish
    # needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows
    if: ${{ github.event_name == 'push' || github.event.pull_request.merged == true }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup QEMU
        uses: docker/setup-qemu-action@v2
      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "lts/*"
          cache: npm
      - name: Setup semantic-release
        run: yarn install
      - name: Pre Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./pre-release.js
      - name: Inject VERSION into workflow
        run: |
          echo VERSION=$(cat VERSION) >> $GITHUB_ENV
        shell: bash
      - name: Check for a bump
        id: bump
        continue-on-error: true
        run: git diff --exit-code VERSION
      - name: Publish GitHub Release on bump
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release -e ./release.js
